#Author: Juan Zegarra
#Date: 24/01/2026
rm(list=ls())

set.seed(100)
#Install packages
install.packages("vegan")
install.packages("gdata")
install.packages("readxl")
install.packages("plot3D")

#Use ape to open alignment, remove duplicate names
library(ape)


align <- read.dna("~/Lcev/NMDS/PNOVA/totalDMER28_muscle3.fasta", format = "fasta")
rownames(align)<-make.unique(rownames(align), sep = "_")
seq_names <- rownames(align)
any(duplicated(seq_names))

# Calculate distance matrix, remember to set best model from MEGA-X
dist_mat <- dist.dna(align, model = "raw", 
                     pairwise.deletion = TRUE,  # Handle gaps pairwise
                     variance = FALSE, as.matrix = TRUE)          # Don't calculate variances

# Convert to matrix for easier viewing/manipulation
dist_matrix <- as.matrix(dist_mat)


# View first 5x5 entries
print(dist_matrix[1:5, 1:5])

# Check dimensions
dim(dist_matrix)

# Get summary statistics
summary(as.vector(dist_matrix))

# Export if needed
write.csv(dist_matrix, "distance_matrix.csv")

#Activate other packages
require(vegan)
library(gdata)
library(readxl)
require(plot3D) 
library(readxl)
library(stringr)
library (vegan3d)
library(ape)
library(dplyr)
library(ggplot2)

#Set dir
setwd("/home/juanzegarra/Lcev/NMDS/PNOVA/28")
setwd("Downloads/")
getwd ()


#Read input tables if not using distance generated by ape
pairwise = read.csv("totalDMER33_distance_corrected.csv")  
pairwise <- totalDMER28_distance

#Adjusting distance matrix not from ape
pairwise2 <- pairwise[,-1]
rownames(pairwise2) <- pairwise[,1]
pairwise2[is.na(pairwise2)] <- 0
# correct if "?" were generated (MEGA tends to generate them if the data doesnt fit the model)
pairwise2 <- pairwise2 %>%
  mutate(across(everything(), ~ as.numeric(.)))
pairwise2[is.na(pairwise2)] <- 0
#
pair.t = pairwise2 + t(pairwise2)
pair.t[1:5, 1:5]

#IF USING MATRIX FROM APE EXECUTE THIS
pair.t = dist_matrix
#NMDS analysis (test in several dimensions, keep the best model)
NMDS <- metaMDS(pair.t, distance = "euclidean", k = 3, try = 100, trymax = 1000)
NMDS2 <- metaMDS(pair.t, distance = "euclidean", k = 2, try = 100, trymax = 1000)
NMDS3 <- metaMDS(pair.t, distance = "euclidean", k = 2, try = 100, trymax = 1000)

NMDS <- metaMDS(pair.t, distance = "euclidean", k = 4, try = 100, trymax = 200, previous.best = NMDS)

#to plot nmds result
NMDS
NMDS2
NMDS3

#Plot 2D (ggplot) 
#(this plot presumes location/group data is stored in the first three characters of the fasta header)
#e.g. >SER_ClusterX_contigY_copy_Z

nmds_points <- as.data.frame(NMDS$points)
nmds_points$Group <- substr(rownames(nmds_points), 1, 3)
nmds_points <- nmds_points %>%
  mutate(Group = toupper(Group))

plot_nmds <-ggplot(nmds_points, aes(MDS1, MDS2, color = Group)) +
  geom_point(size = 4) +
  scale_color_viridis_d(option = "D") +
  theme(legend.background = element_rect("white"), panel.background = element_blank(),
      axis.line = element_line(),
      legend.title = element_blank(),
      legend.key.size = unit(1.5,"lines"),
      legend.text = element_text(size = 12),
      axis.line.x = element_line(linewidth = 1.5),
      axis.line.y = element_line(linewidth = 1.5), 
      axis.text = element_text(size = 10, 
      face = "bold", colour = "black" ) )
ggsave("NMDS_save.pdf", plot = plot_nmds, width = 6, height = 4)

#PERMANOVA
rows<-rownames(dist_mat)
location <- toupper(substr(rows,1,3))
location <- toupper(str_sub(rows, 1, 3))
metadata <- data.frame(
  location = factor(location),
  row.names = rows
)
all(rownames(rows) == labels(pair.t))

library(vegan)

#run PERMANOVA
adonis2(pair.t ~ location, 
        data = metadata,
        permutations = 999)
pairwise_matrix <- as.matrix(pair.t)
pairwise2_dist <- as.dist(as.matrix(pairwise2))

# convert to dist
pair_dist <- as.dist(pair.t)

# Run dispersion test
disp <- betadisper(pair_dist, metadata$location)

# Visualize
plot(disp)
boxplot(disp)

# Statistical test
permutest(disp, permutations = 999)  # Permutation test
anova(disp)                          # Regular ANOVA on distances
# 











